/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "adc.h"
#include "hall.h"
#include "pwm.h"
#include "task.h"
#include "cnv.h"
#include "drv_mng.h"

#define GPIOA_BASE_ADDR 0x40010800u
#define REG32(addr) (*(volatile uint32_t *)(addr))
#define GPIOA_CRL REG32(GPIOA_BASE_ADDR + 0x00u)
#define GPIOA_IDR REG32(GPIOA_BASE_ADDR + 0x08u)

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
volatile int cnt;
volatile uint8_t hall_pattern;
volatile uint8_t pa123_poll_pattern;

int main(void)
{
    ADC_Init();
    Hall_Init();
	PWM_Init();
	eng_cnv_init();
	eng_drv_mng_init();
	eng_task_init();
    GPIOA_CRL &= ~(0xFu << (3u * 4u));
    GPIOA_CRL |= (0x4u << (3u * 4u));

    /* Loop forever */
	while(1)
	{
		cnt++;
        eng_task_main();
	}
}
